DAVFoundation/davfoundation.github.io

README.md
=> fix: link to website closes #4

code_of_conduct.md
A code of conduct was added at the root of the folder. It is based on the 'Contributor Covenant Code of Conduct'.
https://github.com/DAVFoundation/website/issues/3#issuecomment-342875508
No tests were done
=> Added code of conduct (code_of_conduct.md) #3

README.md
Added gitter badge to README.md file
Closes issue #1 
Allows users to access the repo's Gitter from the Readme directly
This PR does not require testing
=> README.md: Added Gitter badge

index.html
=> Added social profiles for team members on website

index.html
Minor Changes to Rachel and Andrews profile based off suggestion by Noam.
=> Minor changes to Rachel and Andrew profile

faq.html
=> Changed company to foundation

faq.html
removed a typo `is` from faqs.
=> fixed typo

README.md
The image has been placed under the badges in the file. These changes were done in vim in bash on Ubuntu on Windows. 
https://github.com/DAVFoundation/davfoundation.github.io/issues/14
This change is required to add the missing screen shot. 
This was tested by observing the changes in GitHub.
=> Added website img (jpg) to README.md file #14

blog.html, contact-us.html, faq.html, index.html, technology.html, temp.html, videos.html
changed the year to 2018 in the copyright
https://github.com/DAVFoundation/davfoundation.github.io/issues/16
=> changed the year to 2018 in the copyright

index.html
=> add ajax request to homepage for inserting transaction id

css/style.css, css/style.scss, index.html, js/main.js
=> email validation

css/style.css, css/style.scss, index.html, js/main.js
=> Adwords handling

index.html
=> upgrade style.css and main.js virsion

index.html
=> add seconds

css/style.css, css/style.scss, index.html, js/main.js, protocols.html
=> increase contributed value with animation

index.html, js/main.js
=> Change 'invalid email' error message (DD-73)

js/token-sale.js
=> fix: uri encode email in token sale

js/main.js, token-sale.html
=> fix: failed status is the same as check required, delete address

css/token-sale.css, css/token-sale.scss, js/token-sale.js
=> bug fix address invisable in safari

index.html, js/main.js, token-sale-details.html
=> update youtube links and another text

js/token-sale.js, token-sale.html
=> bug fix copy to clipboard safari IOS

css/token-sale.css, css/token-sale.scss
=> checkboxes 'move around' in mac/safari (DD-103)

index.html, js/token-sale.js, token-sale.html
=> Add google analytics events

js/token-sale.js
=> feat: trim email in token sale page

index.html, js/main.js
=> floating button hidden in desktop and show on scroll, contact us mail change

js/main.js
=>  uncomment cookie check, change cookie expiration date to 14 days from set

css/style.css, css/style.scss, token-sale.html
=> ui fixes (DD-124, DD-131)

index.html
=> fix: increase versions

index.html
=> Changed HARD CAP position to be under progress bar

index.html, js/main.js
=> fix: floating button animation

css/style.css, css/style.scss, index.html, js/main.js
=> home page style fix (DD-133, DD-134)

css/style.css, css/style.scss, index.html, protocols.html
=> color fix, version update

css/common.scss, css/style.css, css/style.scss, index.html
=> ico-start-box text changes

index.html
=> fix: fixes #DD-146

index.html
=> text change for bottom-alert

index.html
=> version update

index.html
=> feat: mail subscribe post-ico

css/style.css, css/style.scss, token-sale-details.html
=>  Post ICO - Token Sale page changes (DD-154)

css/style.css, css/style.scss, token-sale-details.html
=> Unneeded space between announcement and floating button (DD-156)

css/style.css, css/style.scss, index.html
=>  bug fix (DD-157)

index.html
=> feat: remove selling restriction paragraph

css/style.css, css/style.scss, index.html, token-sale-details.html
=> Use ETH instead of USD for the amount raised number (DD-158)

index.html
=> Post ICO style fix for raised amount

css/style.css, css/style.scss, index.html, js/main.js
=> bug fixes in mobile menu header

css/style.css, css/style.scss
=> fix mobile menu color on scroll

index.html, token-sale-details.html
=> change raised amount number

index.html, token-sale-details.html
=> Type changes requested by Joe

media.html
=> fix tal's name

blockchain-today.html, careers.html, charging-station.html, charging-stations.html, index.html, media.html, privacy-policy.html, products.html, protocols.html, prototypes.html, referral.html, route-creator.html, terms-of-use.html, token-reschedule.html, token-sale-details.html
=> Changed page titles and remove token sales details section

blockchain-today.html, careers.html, charging-station.html, charging-stations.html, index.html, media.html, privacy-policy.html, products.html, protocols.html, prototypes.html, referral.html, route-creator.html, terms-of-use.html, token-reschedule.html, token-sale-details.html, whitelist-prime.html
=> remove unnecessary dependencies

index.html
=> Changed title for Ming

index.html
=> changed title for Alick
